# Exeter Urban Analytics - Exercises

Lecturer: Chico Camargo - f.camargo@exeter.ac.uk

In [1]:
# Don't forget to run this 

import pandas as pd

%matplotlib inline
import seaborn as sns
sns.set('poster')

In [ ]:
# Exercise 1 - Football stats
#
#
# In this exercise, you will take the mean value of some columns in a dataframe.
# This is done using the following command: 
#
# my_dataframe['column_name'].mean()
#
#
# We ask you to:
# 1 -  Load the csv file in 'Euro2012stats.csv' as a dataframe.
# 2 -  Create a new dataframe, containing only the columns Team, Yellow Cards and Red Cards.
# 3a - Filter teams that scored more than 5 goals, and print the mean of the column Goals.
# 3b - Filter teams that scored exactly   5 goals, and print the mean of the column Goals.
# 3c - Filter teams that scored less than 5 goals, and print the mean of the column Goals.
# 3d - Filter teams that scored either more or less than 5 goals (but not 5),
#      and print the mean of the column Goals.

#################################
# Your code below here

In [ ]:
# Exercise 2: More football stats
#
# We ask you to:
# 1 - Load the csv file in 'Euro2012stats.csv' as a dataframe.
#
# 2 - Create a new column in that dataframe, with the number of letters
#     in the name of each country.
#
# 3 - From that dataframe, create a new dataframe containing only the teams
#     that have more than 10 Yellow Cards OR at least one Red Card.
#
# 4 - Sort that new dataframe, according to the column you created in (2),
#     going from the country with the shortest name to the country with the longest name.
#
# 5 - Iterate through the sorted dataframe, printing the name of every country
#     and its 'Saves-to-shots ratio'.

#################################
# Your code below here

In [ ]:
# Exercise 3a: Visualising football stats, part A
#
# For this exercise, you will need two new things:
#
# Here's how to plot a horizontal bar chart:
### my_dataframe['column_name'].plot.barh()
#
# And here's how to change the index of a dataframe to one of its columns:
### my_indexed_dataframe = my_dataframe.set_index('column_name')
#
# With that in mind:
#
# 1 - Load the csv file in 'Euro2012stats.csv' as a dataframe.
#
# 2 - Set the column 'Team' to be its index
#
# 3 - Make a horizontal bar plot of the number of goals per team, 
# but only for the teams that received zero Red Cards.
#
# Tip: increase the figuresize by using the figsize command, as in the lecture notes.

#################################
# Your code below here

In [ ]:
# Exercise 3b: Visualising football stats, part B
#
# To make a histogram, you can use the function presented in the lecture notes:
### my_dataframe['column_name'].hist()
#
# Inside the (), you can put various arguments, listed in the links below:
# - https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.hist.html
# - https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hist.html
# 
# With that in mind:
#
# 1 - Load the csv file in 'Euro2012stats.csv' as a dataframe.
#
# 2 - Make a histogram for the variable 'Hit Woodwork', but only for the teams
# that received zero Red Cards, setting the bins to range(10), and the color to 'skyblue'.
#
# 3 - Make a histogram for the variable 'Hit Woodwork', but only for the teams
#     that received Red Cards, setting the bins to range(10), and the color to 'salmon'.
#
# 4 - Set the ticks on the x axis to range(10) using:
#     my_histogram.set_xticks( range(10)),
#     where my_histogram is the name of your histogram variable.
#
# 5 - Set the xlabel of the histogram to 'number of goals', and
#     the ylabel of the histogram to 'number of teams'.
#
#
#################################
# Your code below here

**Before exercises 4 and 5, first run the code below. But see if you can understand what the code is doing.**

We are going to look which authors comment more or get more likes. Here we have three dictionaries, *comment_count*, *likes_count* and *replies_count*, which have author names as keys, and number of comments, likes and replies as values, respectively. We then make a dataframe based on all that information.

In [2]:
raw_comments = pd.read_csv('IoP18_kpop_comments.tsv', delimiter='\t')

to_filter = ['CommentPublished','CommentTextDisplay','CommentAuthorName',
             'CommentLikeCount','CommentTotalReplyCount','Title']

comments = raw_comments.filter(items=to_filter).dropna()

comment_count = {}
likes_count   = {}
replies_count = {}

for index, row in comments.iterrows():
    
    author = row.CommentAuthorName
    number_of_likes   = int(row.CommentLikeCount)
    number_of_replies = int(row.CommentTotalReplyCount)
    
    # Count comments
    if author not in comment_count:
        comment_count[author]  = 1
    else:
        comment_count[author] += 1
    
    # Count likes
    if author not in likes_count:
        likes_count[author]  = number_of_likes
    else:
        likes_count[author] += number_of_likes
    
    # Count replies
    if author not in replies_count:
        replies_count[author]  = number_of_replies
    else:
        replies_count[author] += number_of_replies


all_authors = comment_count.keys()

data_dict = { 'Author'      :list( all_authors ),
              'CommentCount':list( comment_count.values() ),
              'TotalLikes'  :list( likes_count.values()   ),
              'TotalReplies':list( replies_count.values() ) }

authors = pd.DataFrame(data_dict)

authors.head()

                Author  CommentCount  TotalLikes  TotalReplies
0  Naomi Nicole Yambao             1           0             0
1   Ahmad Farhan Zarin             1           0             0
2       sheridan tulio             1           0             0
3        Seraph Gaming             1           0             0
4     Ashleigh Sharman             1           0             0

In [ ]:
# Exercise 4: Plotting authors
#
# Now that we hava a dataframe containing all authors:
#
# 1 - make a scatter plot with 'CommentCount' in the x axis and 'TotalReplies' in the y axis.
#
# 2 - Set the xlabel of the scatter plot to 'number of comments',
# and the ylabel to 'number of replies'.
#
# 3 - You should find that there is only one Author with over 15 comments and over 200 replies.
# Find the name of that Author by using masks on the dataframe 'authors' and on the variables
# 'CommentCount' and 'TotalReplies' so that you produce a dataframe with a single row,
# containing that Author, as well as their number of comments, likes and replies.
# Finally, display that dataframe using display(that_dataframe).
#
#################################
# Your code below here

In [ ]:
# Exercise 5: Printing full comments
#
# 1 - Sort your dataframe according to 'TotalLikes',
# from the author with most likes to the author with the fewest likes.
#
# 2 - Using the 'comments' dataframe as defined above,
# print all the comments by the author with most likes.

#################################
# Your code below here

In [ ]:
# Exercise 6: K-means vs. DBSCAN clustering
#
# 1 - Using pandas, load the file in 'dublin-trees.csv'.
#     This file contains the Latitude and Longitude of thousands of trees in Dublin.
#     More here: https://data.smartdublin.ie/dataset/trees
#
# 2 - Make a scatter plot showing the spatial distribution of trees.
#
# 3 - Using the K-means clustering algorithm from sklearn, cluster the trees using k = 5, 10, and 15,
#     and make a scatterplot showing the results of each clustering, with one colour for each cluster.
#     K-means: https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html
#
# 4  Using the DBSCAN clustering algorithm from sklearn, cluster the trees setting the 'eps' parameter to 0.01,
#     and make a scatterplot showing the results of each clustering, with one colour for each cluster.
#     (note that this algorithm takes longer to run!)
#     DBSCAN: https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html
#
#################################
# Your code below here